[package]
name = "y2q-warp"
version.workspace = true
edition = "2024"

[[bin]]
name = "y2q-warp"
path = "src/main.rs"

[dependencies]
chrono          = { workspace = true }
clap            = { workspace = true }
crossterm       = { workspace = true }
csv             = { workspace = true }
futures-util    = { workspace = true }
hdrhistogram    = { workspace = true }
humantime       = { workspace = true }
rand            = { workspace = true }
ratatui         = { workspace = true }
reqwest         = { workspace = true }
serde           = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true }
tracing         = { workspace = true }
tracing-subscriber = { workspace = true }
y2q-client      = { path = "../y2q-client" }
y2q-config      = { path = "../y2q-config" }
zeroize         = { workspace = true }
zstd            = { workspace = true }
